import type { Metadata } from "next";
import TwoColumn from "../components/layout/TwoColumn";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <TwoColumn>{children}</TwoColumn>;
}
