import type { Metadata } from "next";
import { notoSansJp } from "./components/util/font";
import Header from "./components/web-parts/Header";
import Footer from "./components/web-parts/Footer";
import "./globals.css";
import StoreProvider from "./components/context/StoreProvider";
import AuthContext from "./components/context/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${notoSansJp.className} flex flex-col min-h-screen`}>
          <AuthContext>
            <Header />
            {children}
            <Footer />
          </AuthContext>
      </body>
    </html>
  );
}
