import type { Metadata } from "next";
import BlogTopInfo from "@/app/components/layouts/BlogTopInfo";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <BlogTopInfo
        title="サンプルタイトル"
        src="/blog-test.webp"
        alt="a"
        date="2024-08-29"
      />
    </>
  );
};

export default page;
