import type { Metadata } from "next";
import DashboardSideMenu from "../components/dashboard/DashboardSideMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="w-full max-w-[1140px] my-12 mx-auto">
      <div className="w-full px-2">{children}</div>
    </main>
  );
}
