import type { Metadata } from "next";
import OneColumn from "../components/layouts/with-children/OneColumn";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <OneColumn>{children}</OneColumn>;
}
